-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsz9/O3BAwxCRHnp57ChLye/C5DJinnYnY+m8yiKDvWugCgYIKoZIzj0DAQehRANCAARFV61TSXPCxcUKXNU5so8Njrhndav/xuCmSQxfJsk5h0RP+KM9bdswtgc/jxEnI2Qa80KVL+ZVI7ZscauA9HH/
-----END PRIVATE KEY-----